# Site settings
title: Jennifer Helsby
email: jen@redshiftzero.com
description: redshiftzero Jennifer Helsby 
baseurl: ""
url: "https://redshiftzero.github.io"
subtitle: musings 
keywords: "Jennifer Helsby, redshiftzero.github.io, redshiftzero"
sosial_username: redshiftzero
simple_search: http://google.com/search
# Build settings
markdown: kramdown
author: redshiftzero
permalink: ":year/:month/:day/:title/"
paginate: 7
paginate_path: "/page/:num/"
